# Generated by Django 3.0.7 on 2020-06-21 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='issue',
            field=models.CharField(choices=[('abandoned', 'abandoned'), ('resolved', 'resolved')], default='abandoned', max_length=25),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 21, 16, 14, 54, 26178)),
        ),
    ]
