# Generated by Django 3.0.7 on 2020-06-21 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20200621_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 21, 16, 30, 43, 596910)),
        ),
        migrations.AlterField(
            model_name='post',
            name='issue',
            field=models.CharField(choices=[('abandoned', 'Abandoned'), ('resolved', 'Resolved')], default='abandoned', max_length=25),
        ),
    ]
