# Generated by Django 3.0.7 on 2020-06-22 12:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_auto_20200621_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agent',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 22, 12, 35, 57, 786079)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 22, 12, 35, 57, 783184)),
        ),
        migrations.CreateModel(
            name='Post_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Agent')),
                ('post_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Post')),
            ],
        ),
    ]
