# Generated by Django 3.0.7 on 2020-06-22 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20200622_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='date_posted',
        ),
        migrations.AddField(
            model_name='agent',
            name='date_commit',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 22, 15, 38, 8, 117364)),
        ),
        migrations.AddField(
            model_name='agent',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 22, 15, 38, 8, 117307)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 22, 15, 38, 8, 115814)),
        ),
    ]
