# Generated by Django 3.0.7 on 2020-06-29 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20200629_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='assigned_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 11, 44, 20, 549287)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 11, 44, 20, 547594)),
        ),
    ]
