# Generated by Django 3.0.7 on 2020-06-30 14:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0011_auto_20200629_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='assigned_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 14, 58, 50, 489602)),
        ),
        migrations.AlterField(
            model_name='agent',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to_user_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 14, 58, 50, 487897)),
        ),
    ]
