# Generated by Django 3.0.7 on 2020-06-30 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20200630_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='assigned_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 15, 50, 20, 242299)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 15, 50, 20, 240613)),
        ),
        migrations.DeleteModel(
            name='Post_status',
        ),
    ]
